export const stockFieldMap = {
  // 最新价
  f2: "currentPrice",
  // 涨跌幅
  f3: "changePercent",
  // 涨跌额
  f4: "changeAmount",
  // 成交量
  f5: "volume",
  // 成交额
  f6: "amount",
  // 振幅
  f7: "amplitude",
  // 换手率
  f8: "turnoverRate",
  // 市盈率
  f9: "peRatio",
  // 量比
  f10: "volumeRatio",
  // 5分钟涨跌幅
  f11: "fiveMinChangePercent",
  // 股票代码
  f12: "symbol",
  // 市场： 0: 深市，1: 沪市
  f13: "market",
  // 股票名称
  f14: "name",
  // 昨收价
  f18: "previousClose",
  // 总市值
  f20: "totalMarketValue",
  // 流通市值
  f21: "circulatingMarketValue",
  // 涨速
  f22: "riseSpeed",
  // 市净率
  f23: "pbRatio",
  // 60日涨跌幅
  f24: "sixtyDayChangePercent",
  // 年初至今涨跌幅
  f25: "ytdChangePercent",
  // 上市日期
  f26: "listingDate",
  // 昨日结算价
  f28: "previousSettlementPrice",
  // 现手
  f30: "currentVolume",
  // 买入价
  f31: "buyPrice",
  // 卖出价
  f32: "sellPrice",
  // 委比
  f33: "orderRatio",
  // 外盘
  f34: "externalVolume",
  // 内盘
  f35: "internalVolume",
  // 人均持股数
  f36: "averageSharesHeld",
  // 净资产收益率(加权)
  f37: "weightedROE",
  // 总股本
  f38: "totalShares",
  // 流通股
  f39: "circulatingShares",
  // 营业收入
  f40: "revenue",
  // 营业收入同比
  f41: "revenueYoY",
  // 营业利润
  f42: "operatingProfit",
  // 投资收益
  f43: "investmentIncome",
  // 利润总额
  f44: "totalProfit",
  // 净利润
  f45: "netProfit",
  // 净利润同比
  f46: "netProfitYoY",
  // 未分配利润
  f47: "undistributedProfit",
  // 每股未分配利润
  f48: "undistributedProfitPerShare",
  // 毛利率
  f49: "grossMargin",
  // 总资产
  f50: "totalAssets",
  // 流动资产
  f51: "currentAssets",
  // 固定资产
  f52: "fixedAssets",
  // 无形资产
  f53: "intangibleAssets",
  // 总负债
  f54: "totalLiabilities",
  // 流动负债
  f55: "currentLiabilities",
  // 长期负债
  f56: "longTermLiabilities",
  // 资产负债比率
  f57: "debtToAssetRatio",
  // 股东权益
  f58: "shareholdersEquity",
  // 股东权益比
  f59: "equityRatio",
  // 公积金
  f60: "capitalReserve",
  // 每股公积金
  f61: "capitalReservePerShare",
  // 主力净流入
  f62: "mainNetInflow",
  // 集合竞价
  f63: "auctionPrice",
  // 超大单流入
  f64: "largeOrderInflow",
  // 超大单流出
  f65: "largeOrderOutflow",
  // 超大单净额
  f66: "largeOrderNetAmount",
  // 超大单净占比
  f69: "largeOrderNetRatio",
  // 大单流入
  f70: "bigOrderInflow",
  // 大单流出
  f71: "bigOrderOutflow",
  // 大单净额
  f72: "bigOrderNetAmount",
  // 大单净占比
  f75: "bigOrderNetRatio",
  // 中单流入
  f76: "mediumOrderInflow",
  // 中单流出
  f77: "mediumOrderOutflow",
  // 中单净额
  f78: "mediumOrderNetAmount",
  // 中单净占比
  f81: "mediumOrderNetRatio",
  // 小单流入
  f82: "smallOrderInflow",
  // 小单流出
  f83: "smallOrderOutflow",
  // 小单净额
  f84: "smallOrderNetAmount",
  // 小单净占比
  f87: "smallOrderNetRatio",
  // 当日DDX
  f88: "dailyDDX",
  // 当日DDY
  f89: "dailyDDY",
  // 当日DDZ
  f90: "dailyDDZ",
  // 5日DDX
  f91: "fiveDayDDX",
  // 5日DDY
  f92: "fiveDayDDY",
  // 10日DDX
  f94: "tenDayDDX",
  // 10日DDY
  f95: "tenDayDDY",
  // DDX飘红天数(连续)
  f97: "continuousDDXRedDays",
  // DDX飘红天数(5日)
  f98: "fiveDayDDXRedDays",
  // DDX飘红天数(10日)
  f99: "tenDayDDXRedDays",
  // 行业
  f100: "industry",
  // 板块领涨股
  f101: "sectorLeadingStock",
  // 地区板块
  f102: "regionSector",
  // 备注
  f103: "remarks",
  // 上涨家数
  f104: "risingStocksCount",
  // 下跌家数
  f105: "fallingStocksCount",
  // 平家家数
  f106: "unchangedStocksCount",
  // 每股收益
  f112: "eps",
  // 每股净资产
  f113: "bookValuePerShare",
  // 市盈率（静）
  f114: "staticPE",
  // 市盈率（TTM）
  f115: "ttmPE",
  // 当前交易时间
  f124: "currentTradingTime",
  // 板块领涨股
  f128: "sectorLeadingStock",
  // 净利润
  f129: "netProfit",
  // 市销率TTM
  f130: "ttmPS",
  // 市现率TTM
  f131: "ttmPCF",
  // 总营业收入TTM
  f132: "ttmTotalRevenue",
  // 股息率
  f133: "dividendYield",
  // 行业板块的成分股数
  f134: "sectorComponentCount",
  // 净资产
  f135: "netAssets",
  // 净利润TTM
  f138: "ttmNetProfit",
  // 更新日期
  f221: "updateDate",
  f233: "",
  f234: "",
  f229: "",
  f230: "",
  f231: "",
  f235: "",
  f236: "",
  f154: "",
  f237: "",
  f238: "",
  f239: "",
  f240: "",
  f241: "",
  f227: "",
  f242: "",
  f243: "",
};

export type StockFieldKeys = keyof typeof stockFieldMap;
